#!/usr/bin/env python3
"""Regenerate 4-process/log.md from git. Derived, so it cannot go stale.

The hand-written version proved the point it was meant to solve: built
2026-08-09, abandoned within the hour, ten commits behind by evening. Stan:
"experience in other venues tells me this only works when it runs
automatically."

A log that is DERIVED cannot rot. Git already holds what happened, in order,
with dates; the log is a view over it. If this file is deleted the log is
regenerable, which is the property the hand-written one never had.

Operation type comes from the commit-subject prefix, which is already how the
messages are written (`fix:`, `check:`, `evidence:` …). Unmapped prefixes pass
through as themselves rather than being forced into a bucket — an honest
"unknown" beats a wrong classification.

Called by loop_health.py, which runs from the SessionStart hook. No new hook,
no new thing to remember.

    python 5-machinery/scripts/build_log.py --check     # would it change?
    python 5-machinery/scripts/build_log.py             # rewrite 4-process/log.md
    python 5-machinery/scripts/build_log.py --calibrate
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

def _find_repo_root():
    """Repo root by MARKER, not by counting parents.

    Counting encodes this file's depth in the tree, so moving the file silently
    breaks it and no text-based check notices. Anchoring on .git survives any
    move. Added 2026-08-10 after a reorg broke three different counted idioms.
    """
    from pathlib import Path as _P
    _here = _P(__file__).resolve()
    for _p in _here.parents:
        if (_p / ".git").exists():
            return _p
    return _here.parent


REPO = _find_repo_root()
LOG = REPO / "4-process" / "log.md"

# Subject prefix -> operation. Deliberately small; anything else passes through.
OPS = {
    "audit": "audit", "security": "audit",
    "evidence": "measure", "check": "measure", "correct": "measure",
    "proposal": "propose", "process": "propose", "decision": "propose",
    "build": "build", "script": "build", "skill": "build", "board": "build",
    "nav": "build", "tasks": "build", "docs": "build",
    "memory": "schema", "promote": "schema", "normalize": "schema",
    "fix": "fix", "untrack": "fix", "revert": "fix",
    "deploy": "deploy",
}

HEADER = """# Operations log

**Derived from `git log` — do not hand-edit.** Regenerated by
`5-machinery/scripts/build_log.py`, which `loop_health.py` calls at every session start.

The hand-written version of this file was built 2026-08-09 and was ten commits
stale by that evening, which is the whole argument for deriving it: git already
records what happened, so a log that reads from git cannot fall behind. The
operation type comes from the commit-subject prefix; unmapped prefixes pass
through as themselves rather than being guessed at.

Distinct from its two neighbours: `2-evidence/approval-log.jsonl` records what
the **system** decided, `4-process/lessons.md` records **corrections** awaiting
promotion. This records what **we did**.

---

"""


def commits(limit=80):
    out = subprocess.run(
        ["git", "log", f"-{limit}", "--no-merges",
         "--format=%ad\x1f%h\x1f%s", "--date=short"],
        cwd=REPO, capture_output=True, text=True,
        encoding="utf-8", errors="replace").stdout
    rows = []
    for line in out.splitlines():
        if line.count("\x1f") != 2:
            continue
        date, sha, subject = line.split("\x1f")
        m = re.match(r"^([a-z][a-z-]*):\s*(.+)$", subject)
        op = OPS.get(m.group(1), m.group(1)) if m else "—"
        title = m.group(2) if m else subject
        rows.append((date, op, sha, title))
    return rows


def render(rows):
    body = []
    for date, op, sha, title in rows:
        body.append(f"## [{date}] {op} | {title}\n\n`{sha}`\n")
    return HEADER + "\n".join(body)


def calibrate() -> bool:
    ok = True
    cases = [
        ("fix: something broke", "fix", "prefix maps to its operation"),
        ("check: a new detector", "measure", "check maps to measure"),
        ("wibble: an unmapped prefix", "wibble", "unmapped passes through, not guessed"),
        ("no prefix at all here", "—", "no prefix yields no operation"),
    ]
    for subject, expect, why in cases:
        m = re.match(r"^([a-z][a-z-]*):\s*(.+)$", subject)
        got = OPS.get(m.group(1), m.group(1)) if m else "—"
        hit = got == expect
        ok &= hit
        print(f"  [{'PASS' if hit else 'FAIL'}] {why} — got {got!r}")
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--calibrate", action="store_true")
    args = ap.parse_args()

    if args.calibrate:
        print("calibration — prefix mapping must classify and must not invent")
        ok = calibrate()
        print("\nCALIBRATED" if ok else "\nMISCALIBRATED")
        return 0 if ok else 1

    if not calibrate():
        print("MISCALIBRATED — refusing to write", file=sys.stderr)
        return 1

    new = render(commits())
    old = LOG.read_text(encoding="utf-8") if LOG.exists() else ""
    if new == old:
        print("log.md already current")
        return 0
    if args.check:
        print(f"log.md would change ({len(new.splitlines())} lines)")
        return 0
    LOG.write_text(new, encoding="utf-8", newline="\n")
    print(f"log.md regenerated — {len(commits())} operations")
    return 0


if __name__ == "__main__":
    sys.exit(main())
